# The settings below replicate the github-pages environment for parity in development rendering.

# References (describing github-pages's defaults and overrides):
# * https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
# * https://help.github.com/articles/configuring-jekyll/
# * https://help.github.com/articles/configuring-jekyll-plugins

## forced settings ##
lsi: false
safe: true
# source: <set dynamically>
incremental: false
highlighter: rouge
gist:
  noscript: false

## defaults, but not forced ##
encoding: UTF-8
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

kramdown:
  ## forced ##
  input: GFM
  hard_wrap: false
  ## defaults ##
  math_engine: mathjax
  syntax_highlighter: rouge

# customizations

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
